version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: nhanhuynh/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: "Build && Push "
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker build -t "$DOCKER_IMAGE:$DOCKER_TAG" .
            docker push nhanhuynh/react-docker:latest
      - run:
          name: "Docker Logout"
          when: always
          command: docker logout
          

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-deploy:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
